In [5]:
import numpy as np
import pandas as pd

In [6]:
sensor_data = pd.read_csv("PressureSensorData.csv")

In [7]:
sensor_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   test_id   107 non-null    float64
 1   pt_psia   108 non-null    int64
 2   pa_psia   108 non-null    int64
 3   pd_volts  108 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 3.5 KB

In [8]:
sensor_data

     test_id  pt_psia  pa_psia  pd_volts
0        1.0        5        4    0.2834
1        1.0       10       10    0.3655
2        1.0       15       14    0.4469
3        1.0       35       34    0.7752
4        1.0       55       56    1.1028
..       ...      ...      ...       ...
103      9.0      105      104    1.9267
104      9.0      125      124    2.2536
105      9.0      145      144    2.5820
106      9.0      165      164    2.9100
107      9.0      175      174    3.0690

[108 rows x 4 columns]

In [9]:
new_readings = {"test_id": "U1", "pt_psia": None, "pa_psia": None, "pd_volts": 0.4346}

In [10]:
new_readings = {"test_id": "U1", "pt_psia": None, "pa_psia": None, "pd_volts": 0.4346}
sensor_data = pd.concat([sensor_data, pd.DataFrame([new_readings])], ignore_index=True)

In [11]:
sensor_data

    test_id pt_psia pa_psia  pd_volts
0       1.0       5       4    0.2834
1       1.0      10      10    0.3655
2       1.0      15      14    0.4469
3       1.0      35      34    0.7752
4       1.0      55      56    1.1028
..      ...     ...     ...       ...
104     9.0     125     124    2.2536
105     9.0     145     144    2.5820
106     9.0     165     164    2.9100
107     9.0     175     174    3.0690
108      U1    None    None    0.4346

[109 rows x 4 columns]

In [12]:
sensor_data.to_csv("LinearModelData.csv")

### testing ground

In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

sensor_data = pd.read_csv("PressureSensorData.csv")
sensor_data.rename(columns = {"pt_psia": "actual", "pa_psia": "analog", "pd_volts": "transducer"}, inplace = True)

#splitting data
X = sensor_data[["analog"]]
y = sensor_data["actual"]

# using a 80 - 20 split for the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

model = LinearRegression()
model.fit(X_train, y_train)

#predict new values
y_pred = model.predict(X_test)

In [16]:
print(X_train)

     analog
64       54
26       15
22      164
31      104
47      174
..      ...
71      174
14       14
92      124
51       34
102      95

[86 rows x 1 columns]

In [10]:
y_pred

array([ 74.91612661, 165.22718087,  56.85391576, 175.26174245,
        14.70875711, 105.01981136,  94.98524978, 145.1580577 ,
       175.26174245, 175.26174245, 145.1580577 , 105.01981136,
         4.67419552, 125.08893453,  94.98524978, 145.1580577 ,
       125.08893453,  54.84700344, 165.22718087,  94.98524978,
         4.67419552,   6.68110784])

In [1]:
from linear_model import LinearModel

In [2]:
lin_model = LinearModel()

loading wrong one:

Loading in the Dataset from LinearModelData.csv...

Dataset successfully loaded.

Training model...
Model ready to be used

In [3]:
lin_model.interface()

This is your Linear Model Interface!

Choose one of the following commands: exit, retrain, update, predict, load, reload:  predict

Please input a voltage to predict a value 0.3

The predicted pressure is 8.31 PSIG

Choose one of the following commands: exit, retrain, update, predict, load, reload:  exit

All data saved. Terminating

In [11]:
volt_pred = pd.DataFrame({"transducer": [5]})

In [12]:
volt_pred

   transducer
0           5

In [3]:
import os

In [4]:
os.path.exists("LinearModelData.csv")

False