In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [3]:
a = pd.DataFrame([[1,2],[2,3]])

In [4]:
print(a.shape)

(2, 2)

In [5]:
class test ():
    def __init__ (self):
        pass
    def __getitem__ (self, key):
        print(f"Your Key is: {key}")
    def __str__ (self):
        return "why not?"

coolthing = test()
coolthing[1]

Your Key is: 1

In [6]:
print(coolthing)

why not?

In [7]:
# three arguments in dataframe, the actal data and the row and column names
b = pd.DataFrame([[1,2], [2,3]], ["Row 1", "Row 2"],["Column 1", "Column 2"])
print(b)

       Column 1  Column 2
Row 1         1         2
Row 2         2         3

In [8]:
fin_dict = {"Revenue": [1231, 2343, 4564, 3345], "Expenses": [1200, 2300, 4500, 3300]}
quarters = ["Q1", "Q2", "Q3", "Q4"]

fin_data = pd.DataFrame(fin_dict, quarters)
fin_data

    Revenue  Expenses
Q1     1231      1200
Q2     2343      2300
Q3     4564      4500
Q4     3345      3300

## indexing DataFrames

In [9]:
print(fin_data.loc["Q1":"Revenue"])

    Revenue  Expenses
Q1     1231      1200
Q2     2343      2300
Q3     4564      4500
Q4     3345      3300

In [17]:
fin_data.iloc[1:]

    Revenue  Expenses
Q2     2343      2300
Q3     4564      4500
Q4     3345      3300

In [24]:
fin_data[fin_data["Revenue"] > 3000]
#myframe2[(myframe2["Q1"]>5)&(myframe2["Q4"]>4)]

    Revenue  Expenses
Q3     4564      4500
Q4     3345      3300

In [19]:
fin_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Q1 to Q4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Revenue   4 non-null      int64
 1   Expenses  4 non-null      int64
dtypes: int64(2)
memory usage: 268.0+ bytes

In [21]:
fin_data.describe()

           Revenue     Expenses
count     4.000000     4.000000
mean   2870.750000  2825.000000
std    1421.185978  1408.012784
min    1231.000000  1200.000000
25%    2065.000000  2025.000000
50%    2844.000000  2800.000000
75%    3649.750000  3600.000000
max    4564.000000  4500.000000

In [26]:
fin_data[["Revenue", "Expenses"]]

    Revenue  Expenses
Q1     1231      1200
Q2     2343      2300
Q3     4564      4500
Q4     3345      3300