#                 1. creating dataframes

## 1.a. from lists

In [1]:
import numpy as n

import pandas as p

In [2]:
p.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [3]:
a=p.DataFrame([[1,2,3],[4,5,6]])

In [4]:
a

   0  1  2
0  1  2  3
1  4  5  6

In [5]:
a.shape

(2, 3)

In [6]:
myframe1=p.DataFrame([[1,1,1,1,1],[2,2,n.NaN,2,2],[1,3,3,3,3],[4,4,4,4,4],[5,5,5,5]],columns=["col1","col2","col3","col4","col5"])
myframe1

   col1  col2  col3  col4  col5
0     1     1   1.0     1   1.0
1     2     2   NaN     2   2.0
2     1     3   3.0     3   3.0
3     4     4   4.0     4   4.0
4     5     5   5.0     5   NaN

In [7]:
myframe=p.DataFrame([[1,1,1,1,1],[2,2,2,2],[1,3,3,3,3],[4,4,4,4,4],[5,5,5,5]],["row1","row2","row3","row4","row5"],["col1","col2","col3","col4","col5"])
myframe

      col1  col2  col3  col4  col5
row1     1     1     1     1   1.0
row2     2     2     2     2   NaN
row3     1     3     3     3   3.0
row4     4     4     4     4   4.0
row5     5     5     5     5   NaN

In [8]:
myframe2=p.DataFrame([[10,3,9,4,10],[3,5,3,7,2],[10,3,5,8,6],[4,8,7,5,9],[5,0,3,7,8]],[11243215,12139710,11308967,12761120,11184978],["Q1","Q2","Q3","Q4","Q5"])
myframe2

          Q1  Q2  Q3  Q4  Q5
11243215  10   3   9   4  10
12139710   3   5   3   7   2
11308967  10   3   5   8   6
12761120   4   8   7   5   9
11184978   5   0   3   7   8

In [9]:
## the uses of range() function to create row and column header
myframe3=p.DataFrame([[1,1,1,1,1],[2,2,2,2,2],[1,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]],range(2,12,2),["col1","col2","col3","col4","col5"]) 
myframe3

    col1  col2  col3  col4  col5
2      1     1     1     1     1
4      2     2     2     2     2
6      1     3     3     3     3
8      4     4     4     4     4
10     5     5     5     5     5

In [10]:
myframe4=p.DataFrame([[1,1,1,1,1],[2,2,2,2,2],[1,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]],range(5),range(3,16,3)) 
myframe4

   3   6   9   12  15
0   1   1   1   1   1
1   2   2   2   2   2
2   1   3   3   3   3
3   4   4   4   4   4
4   5   5   5   5   5

## 1.b.from dictionaries

In [11]:
mydata={"Name":["Harry","Johnson","Peter","Ali","Jane","Smith","Amanda","Sophia"],"State":["TX","NY","TX","NY","NY","CA","CA","TX"],"Total Score":[82,69,98,76,n.NaN,88,90,70],"Age":[20,21,24,25,20,27,26,23]}
std_id=[11243215,12139710,11308967,12761120,11184978,10234126,11896756,11186755]
mydf=p.DataFrame(mydata,std_id)
mydf

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

## 1.c.from external files

In [12]:
irisdata=p.read_csv("iris-data.csv")

irisdata

FileNotFoundError: [Errno 2] No such file or directory: 'iris-data.csv'

# 2. locating elements in a dataframe: use of .loc and .iloc

.loc method works with exact row and columns headers

.iloc method works with positional indices of rows and columns

## 2a .loc

In [26]:
myframe
print(type(myframe.loc[:, "col1"]))

<class 'pandas.core.series.Series'>

In [27]:
myframe.loc["row4","col2"]
type(myframe.loc["row4","col2"])

numpy.int64

In [28]:
myframe.loc["row1":"row4","col1":"col2"]# [start:stop]
#type(myframe.loc["row1":"row4","col1":"col2"])

      col1  col2
row1     1     1
row2     2     2
row3     1     3
row4     4     4

In [15]:
myframe.loc[::2,"col2"::2] # [start:stop:step]

      col2  col4
row1     1     1
row3     3     3
row5     5     5

In [19]:
print(myframe.loc[:,"col2"])
type(myframe.loc[:,"col2"])

row1    1
row2    2
row3    3
row4    4
row5    5
Name: col2, dtype: int64

pandas.core.series.Series

In [20]:
myframe[["col1"]]

      col1
row1     1
row2     2
row3     1
row4     4
row5     5

In [21]:
#myframe[2] # you cant do like this!

## 2b .iloc

In [22]:
myframe.iloc[:,2]

row1    1
row2    2
row3    3
row4    4
row5    5
Name: col3, dtype: int64

In [23]:
myframe.iloc[0:3,1:3]

      col2  col3
row1     1     1
row2     2     2
row3     3     3

## 2c indexing with conditions

In [24]:
#myframe2[["Q2"]]

In [25]:
#myframe2[["Q1","Q3"]]

In [26]:
myframe

      col1  col2  col3  col4  col5
row1     1     1     1     1   1.0
row2     2     2     2     2   NaN
row3     1     3     3     3   3.0
row4     4     4     4     4   4.0
row5     5     5     5     5   NaN

myframe[(myframe["col1"]>2)&(myframe["col1"]<5)]

In [29]:
new=myframe[(myframe["col1"]>2)&(myframe["col1"]<5)] # note the use of & and | operators, instead of "and" and "or"

In [30]:
new

      col1  col2  col3  col4  col5
row4     4     4     4     4   4.0

In [31]:
myframe2

          Q1  Q2  Q3  Q4  Q5
11243215  10   3   9   4  10
12139710   3   5   3   7   2
11308967  10   3   5   8   6
12761120   4   8   7   5   9
11184978   5   0   3   7   8

In [32]:
myframe2[(myframe2["Q1"]>5)&(myframe2["Q4"]>4)]

          Q1  Q2  Q3  Q4  Q5
11308967  10   3   5   8   6

In [33]:
myframe2[(myframe2["Q2"]>4)|(myframe2["Q5"]>6)] 
## co

          Q1  Q2  Q3  Q4  Q5
11243215  10   3   9   4  10
12139710   3   5   3   7   2
12761120   4   8   7   5   9
11184978   5   0   3   7   8

# 3. get the properties of a dataframe

In [34]:
myframe.shape

(5, 5)

In [35]:
myframe.size

25

In [36]:
mydf

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

In [35]:
mydf.head(10)

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

In [36]:
mydf.tail()

            Name State  Total Score  Age
12761120     Ali    NY         76.0   25
11184978    Jane    NY          NaN   20
10234126   Smith    CA         88.0   27
11896756  Amanda    CA         90.0   26
11186755  Sophia    TX         70.0   23

In [37]:
mydf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 11243215 to 11186755
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         8 non-null      object
 1   State        8 non-null      object
 2   Total Score  7 non-null      float64
 3   Age          8 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 320.0+ bytes

In [38]:
mydf.describe()

       Total Score        Age
count     7.000000   8.000000
mean     81.857143  23.250000
std      10.838643   2.712405
min      69.000000  20.000000
25%      73.000000  20.750000
50%      82.000000  23.500000
75%      89.000000  25.250000
max      98.000000  27.000000

In [39]:
z=mydf.describe()
type(z)

pandas.core.frame.DataFrame

In [40]:
z.loc["std","Age"]

2.712405363721075

# 4. functions on dataframe

In [41]:
mydf

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

In [42]:
## get average score and age of all students aged above 23
x=mydf[(mydf["Age"]>23)]
x[["Total Score","Age"]].mean()

Total Score    88.0
Age            25.5
dtype: float64

In [43]:
## get average age of all students aged above 23 and from California
mydf[(mydf["Age"]>23)&(mydf["State"]=="CA")]["Age"].mean()

26.5

In [44]:
# axis=1 means applying the function row-wise 
# axis=0 means defualt, column wise application of a function
# example:
test=p.DataFrame([["John",79,85,81],["Kelly",91,82,87]],columns=["Name","Exam1","Exam2","Exam3"])
test

    Name  Exam1  Exam2  Exam3
0   John     79     85     81
1  Kelly     91     82     87

In [37]:
## apply the mean function over all columns except the first
## the iloc is used here for concvenience, to select from column 1 to 3
test.iloc[:,1:].mean(axis=1)

NameError: name 'test' is not defined

In [38]:
# applying a function on a specific column
mydf["Age"].mean()

23.25

In [39]:
mydf

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

In [40]:
# applying a function on selected rows of a dataframe
mydf[mydf["Total Score"]>=80].mean()

TypeError: Could not convert ['HarryPeterSmithAmanda' 'TXTXCACA'] to numeric

In [ ]:
# applying a function on a specific column of the selected rows of a dataframe
mydf[mydf["Total Score"]>=80]["Total Score"].mean()

In [ ]:
# try this: you will get an error as the mean function only acted upon 
# Total score column!
mydf[mydf["Total Score"]>=80]["Total Score"].mean()["Age"]

The difference between the above 2 cells is: the first one is about applying the function on only a selected column of the selected rows, the second one is about applying the function on all the columns of the selected rows, but viewing on of them.

##### Try the following functions on different dataframes:

.sum()

.min()

.max()

# 5. dealing with NaN

In [41]:
## insert some null values
test=p.DataFrame([["John",79,85,81],["Kelly",91,n.NaN,87],[n.nan,67,85,90]],columns=["Name","Exam1","Exam2","Exam3"])

In [42]:
test

    Name  Exam1  Exam2  Exam3
0   John     79   85.0     81
1  Kelly     91    NaN     87
2    NaN     67   85.0     90

### dropping the rows/columns

In [43]:
test

    Name  Exam1  Exam2  Exam3
0   John     79   85.0     81
1  Kelly     91    NaN     87
2    NaN     67   85.0     90

In [44]:
## removing NaN data
## removing  entire row that contains at least 1 NaN
test_dropped=test.dropna() 
test_dropped

   Name  Exam1  Exam2  Exam3
0  John     79   85.0     81

In [45]:
## removing rows having NaN in specific columns

test.dropna(subset=["Exam2","Exam1"],inplace=True) 
test

   Name  Exam1  Exam2  Exam3
0  John     79   85.0     81
2   NaN     67   85.0     90

In [46]:
test

   Name  Exam1  Exam2  Exam3
0  John     79   85.0     81
2   NaN     67   85.0     90

In [47]:
test_dropped=test.dropna(axis=1) 
test_dropped

   Exam1  Exam2  Exam3
0     79   85.0     81
2     67   85.0     90

### replace the nulls

In [48]:
## replace/fillup NaN with 0
test_filled1=test.fillna(0) # replace all null values wth 0
test_filled1

   Name  Exam1  Exam2  Exam3
0  John     79   85.0     81
2     0     67   85.0     90

In [49]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    1 non-null      object
 1   Exam1   2 non-null      int64
 2   Exam2   2 non-null      float64
 3   Exam3   2 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 80.0+ bytes

In [52]:
# fill the nulls in Name column with N/A and the nulls in Exam3 with the average of the Exam3 
test_filled3=test.fillna({"Name":"N/A","Exam2":test["Exam2"].mean()}) 
# use a dictionary to provide the filler values. 
# keys of the dictionary are the columns names, values are the substitutes for nulls in respective columns
test_filled3

    Name  Exam1  Exam2  Exam3
0   John     79     85     81
1  Kelly     91     82     87

In [53]:
test

    Name  Exam1  Exam2  Exam3
0   John     79     85     81
1  Kelly     91     82     87

In [54]:
# replace the NaN by rowwise average. 
''''NOTE: it works fine for this case, 
 if you have more than one rows having nulls on the same column, your code will be 
 more complicated '''

test_filled3=test.fillna({"Name":"N/A","Exam2":test.iloc[1,1:].mean()})
test_filled3

    Name  Exam1  Exam2  Exam3
0   John     79     85     81
1  Kelly     91     82     87

# 6. Modifying a dataframe

## 6a. sorting

In [55]:
mydf

             Name State  Total Score  Age
11243215    Harry    TX         82.0   20
12139710  Johnson    NY         69.0   21
11308967    Peter    TX         98.0   24
12761120      Ali    NY         76.0   25
11184978     Jane    NY          NaN   20
10234126    Smith    CA         88.0   27
11896756   Amanda    CA         90.0   26
11186755   Sophia    TX         70.0   23

In [56]:
sortdf=mydf.sort_values("Total Score",ascending=False,inplace=True) #by default sort in asc order
sortdf

In [57]:
mydf

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20

In [58]:
mydf.sort_values("Total Score",ascending=False,inplace=True)

In [59]:
mydf

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20

## 6b. combining dataframes/ appending new rows
### -->  concatenating

In [60]:
mydf

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20

In [61]:
mydict2={"Name":["George","Henry","Eliza"],"State":["MN","WA","PA"],"Total Score":[69,92,92],"Age":[21,24,23]}
df=p.DataFrame(mydict2)

In [62]:
df

     Name State  Total Score  Age
0  George    MN           69   21
1   Henry    WA           92   24
2   Eliza    PA           92   23

In [63]:
mydf2=p.concat([mydf,df])  #try with ignore_index

In [64]:
mydf2

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20
0          George    MN         69.0   21
1           Henry    WA         92.0   24
2           Eliza    PA         92.0   23

In [65]:
mydf3=p.concat([mydf2,df],ignore_index=True) 
mydf3

       Name State  Total Score  Age
0     Peter    TX         98.0   24
1    Amanda    CA         90.0   26
2     Smith    CA         88.0   27
3     Harry    TX         82.0   20
4       Ali    NY         76.0   25
5    Sophia    TX         70.0   23
6   Johnson    NY         69.0   21
7      Jane    NY          NaN   20
8    George    MN         69.0   21
9     Henry    WA         92.0   24
10    Eliza    PA         92.0   23
11   George    MN         69.0   21
12    Henry    WA         92.0   24
13    Eliza    PA         92.0   23

## 6c.  reset index

In [66]:
mydf

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20

In [67]:
mydfreset=mydf.reset_index()

In [68]:
mydfreset

      index     Name State  Total Score  Age
0  11308967    Peter    TX         98.0   24
1  11896756   Amanda    CA         90.0   26
2  10234126    Smith    CA         88.0   27
3  11243215    Harry    TX         82.0   20
4  12761120      Ali    NY         76.0   25
5  11186755   Sophia    TX         70.0   23
6  12139710  Johnson    NY         69.0   21
7  11184978     Jane    NY          NaN   20

In [69]:
mydfreset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        8 non-null      int64
 1   Name         8 non-null      object
 2   State        8 non-null      object
 3   Total Score  7 non-null      float64
 4   Age          8 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 452.0+ bytes

## 6d. inserting columns

In [70]:
mydf

             Name State  Total Score  Age
11308967    Peter    TX         98.0   24
11896756   Amanda    CA         90.0   26
10234126    Smith    CA         88.0   27
11243215    Harry    TX         82.0   20
12761120      Ali    NY         76.0   25
11186755   Sophia    TX         70.0   23
12139710  Johnson    NY         69.0   21
11184978     Jane    NY          NaN   20

In [71]:
# appending a new column 
mydf["Last name initial"]=["M","P","I","L","R","W","Q","T"]
mydf

             Name State  Total Score  Age Last name initial
11308967    Peter    TX         98.0   24                 M
11896756   Amanda    CA         90.0   26                 P
10234126    Smith    CA         88.0   27                 I
11243215    Harry    TX         82.0   20                 L
12761120      Ali    NY         76.0   25                 R
11186755   Sophia    TX         70.0   23                 W
12139710  Johnson    NY         69.0   21                 Q
11184978     Jane    NY          NaN   20                 T

In [72]:
# inserting a new columns at a preferred index position
mydf.insert(2,"Major",["ME","EE","CE","PE","EE","ME","ME","CE"]) ##mydf.insert(column index, column header, column values in list)

In [73]:
mydf

             Name State Major  Total Score  Age Last name initial
11308967    Peter    TX    ME         98.0   24                 M
11896756   Amanda    CA    EE         90.0   26                 P
10234126    Smith    CA    CE         88.0   27                 I
11243215    Harry    TX    PE         82.0   20                 L
12761120      Ali    NY    EE         76.0   25                 R
11186755   Sophia    TX    ME         70.0   23                 W
12139710  Johnson    NY    ME         69.0   21                 Q
11184978     Jane    NY    CE          NaN   20                 T

## 6d. renaming columns

In [74]:
myframe

      col1  col2  col3  col4  col5
row1     1     1     1     1   1.0
row2     2     2     2     2   NaN
row3     1     3     3     3   3.0
row4     4     4     4     4   4.0
row5     5     5     5     5   NaN

In [75]:
mf_renamed=myframe.rename(columns={"col1":"C1","col2":"C2","col3":"C3"},inplace=True) # a new dataframe has been created that contains the changes
print(mf_renamed)
#mf_renamed

None

In [76]:
## note that the original dataframe remains unchanged
myframe

      C1  C2  C3  col4  col5
row1   1   1   1     1   1.0
row2   2   2   2     2   NaN
row3   1   3   3     3   3.0
row4   4   4   4     4   4.0
row5   5   5   5     5   NaN

In [77]:
# making changes in the original dataframe:
myframe.rename(columns={"col1":"C1","col2":"C2","col3":"C3"},inplace=True) # note the inplace parameter

In [78]:
myframe

      C1  C2  C3  col4  col5
row1   1   1   1     1   1.0
row2   2   2   2     2   NaN
row3   1   3   3     3   3.0
row4   4   4   4     4   4.0
row5   5   5   5     5   NaN

**********************
## study and learn more at: https://sparkbyexamples.com/pandas/pandas-dataframe-tutorial-beginners-guide/
***********